/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tcpl.sas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EvalVendor service. Represents a row in the &quot;evalvendor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tcpl.sas.model.impl.EvalVendorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tcpl.sas.model.impl.EvalVendorImpl</code>.
 * </p>
 *
 * @author Rakshansh
 * @see EvalVendor
 * @generated
 */
@ProviderType
public interface EvalVendorModel extends BaseModel<EvalVendor> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eval vendor model instance should use the {@link EvalVendor} interface instead.
	 */

	/**
	 * Returns the primary key of this eval vendor.
	 *
	 * @return the primary key of this eval vendor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this eval vendor.
	 *
	 * @param primaryKey the primary key of this eval vendor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the eval vendor ID of this eval vendor.
	 *
	 * @return the eval vendor ID of this eval vendor
	 */
	public long getEvalVendorId();

	/**
	 * Sets the eval vendor ID of this eval vendor.
	 *
	 * @param evalVendorId the eval vendor ID of this eval vendor
	 */
	public void setEvalVendorId(long evalVendorId);

	/**
	 * Returns the emp name of this eval vendor.
	 *
	 * @return the emp name of this eval vendor
	 */
	@AutoEscape
	public String getEmpName();

	/**
	 * Sets the emp name of this eval vendor.
	 *
	 * @param empName the emp name of this eval vendor
	 */
	public void setEmpName(String empName);

	/**
	 * Returns the emp email of this eval vendor.
	 *
	 * @return the emp email of this eval vendor
	 */
	@AutoEscape
	public String getEmpEmail();

	/**
	 * Sets the emp email of this eval vendor.
	 *
	 * @param empEmail the emp email of this eval vendor
	 */
	public void setEmpEmail(String empEmail);

	/**
	 * Returns the audio ID of this eval vendor.
	 *
	 * @return the audio ID of this eval vendor
	 */
	public long getAudioId();

	/**
	 * Sets the audio ID of this eval vendor.
	 *
	 * @param audioId the audio ID of this eval vendor
	 */
	public void setAudioId(long audioId);

	/**
	 * Returns the audio path of this eval vendor.
	 *
	 * @return the audio path of this eval vendor
	 */
	@AutoEscape
	public String getAudioPath();

	/**
	 * Sets the audio path of this eval vendor.
	 *
	 * @param audioPath the audio path of this eval vendor
	 */
	public void setAudioPath(String audioPath);

	/**
	 * Returns the video ID of this eval vendor.
	 *
	 * @return the video ID of this eval vendor
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this eval vendor.
	 *
	 * @param videoId the video ID of this eval vendor
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the video path of this eval vendor.
	 *
	 * @return the video path of this eval vendor
	 */
	@AutoEscape
	public String getVideoPath();

	/**
	 * Sets the video path of this eval vendor.
	 *
	 * @param videoPath the video path of this eval vendor
	 */
	public void setVideoPath(String videoPath);

	/**
	 * Returns the image ID of this eval vendor.
	 *
	 * @return the image ID of this eval vendor
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this eval vendor.
	 *
	 * @param imageId the image ID of this eval vendor
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the image path of this eval vendor.
	 *
	 * @return the image path of this eval vendor
	 */
	@AutoEscape
	public String getImagePath();

	/**
	 * Sets the image path of this eval vendor.
	 *
	 * @param imagePath the image path of this eval vendor
	 */
	public void setImagePath(String imagePath);

	/**
	 * Returns the group ID of this eval vendor.
	 *
	 * @return the group ID of this eval vendor
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this eval vendor.
	 *
	 * @param groupId the group ID of this eval vendor
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this eval vendor.
	 *
	 * @return the user ID of this eval vendor
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this eval vendor.
	 *
	 * @param userId the user ID of this eval vendor
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this eval vendor.
	 *
	 * @return the user uuid of this eval vendor
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this eval vendor.
	 *
	 * @param userUuid the user uuid of this eval vendor
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this eval vendor.
	 *
	 * @return the create date of this eval vendor
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this eval vendor.
	 *
	 * @param createDate the create date of this eval vendor
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this eval vendor.
	 *
	 * @return the modified date of this eval vendor
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this eval vendor.
	 *
	 * @param modifiedDate the modified date of this eval vendor
	 */
	public void setModifiedDate(Date modifiedDate);

}