/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tcpl.sas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RequirementData service. Represents a row in the &quot;requirementdata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tcpl.sas.model.impl.RequirementDataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tcpl.sas.model.impl.RequirementDataImpl</code>.
 * </p>
 *
 * @author Rakshansh
 * @see RequirementData
 * @generated
 */
@ProviderType
public interface RequirementDataModel extends BaseModel<RequirementData> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a requirement data model instance should use the {@link RequirementData} interface instead.
	 */

	/**
	 * Returns the primary key of this requirement data.
	 *
	 * @return the primary key of this requirement data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this requirement data.
	 *
	 * @param primaryKey the primary key of this requirement data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this requirement data.
	 *
	 * @return the uuid of this requirement data
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this requirement data.
	 *
	 * @param uuid the uuid of this requirement data
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the requirement data ID of this requirement data.
	 *
	 * @return the requirement data ID of this requirement data
	 */
	public long getRequirementDataId();

	/**
	 * Sets the requirement data ID of this requirement data.
	 *
	 * @param requirementDataId the requirement data ID of this requirement data
	 */
	public void setRequirementDataId(long requirementDataId);

	/**
	 * Returns the skill set ID of this requirement data.
	 *
	 * @return the skill set ID of this requirement data
	 */
	@AutoEscape
	public String getSkillSetId();

	/**
	 * Sets the skill set ID of this requirement data.
	 *
	 * @param skillSetId the skill set ID of this requirement data
	 */
	public void setSkillSetId(String skillSetId);

	/**
	 * Returns the experience of this requirement data.
	 *
	 * @return the experience of this requirement data
	 */
	public long getExperience();

	/**
	 * Sets the experience of this requirement data.
	 *
	 * @param experience the experience of this requirement data
	 */
	public void setExperience(long experience);

	/**
	 * Returns the jd of this requirement data.
	 *
	 * @return the jd of this requirement data
	 */
	@AutoEscape
	public String getJd();

	/**
	 * Sets the jd of this requirement data.
	 *
	 * @param jd the jd of this requirement data
	 */
	public void setJd(String jd);

	/**
	 * Returns the budget of this requirement data.
	 *
	 * @return the budget of this requirement data
	 */
	public long getBudget();

	/**
	 * Sets the budget of this requirement data.
	 *
	 * @param budget the budget of this requirement data
	 */
	public void setBudget(long budget);

	/**
	 * Returns the remarks of this requirement data.
	 *
	 * @return the remarks of this requirement data
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this requirement data.
	 *
	 * @param remarks the remarks of this requirement data
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the status of this requirement data.
	 *
	 * @return the status of this requirement data
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this requirement data.
	 *
	 * @param status the status of this requirement data
	 */
	public void setStatus(String status);

	/**
	 * Returns the group ID of this requirement data.
	 *
	 * @return the group ID of this requirement data
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this requirement data.
	 *
	 * @param groupId the group ID of this requirement data
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this requirement data.
	 *
	 * @return the user ID of this requirement data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this requirement data.
	 *
	 * @param userId the user ID of this requirement data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this requirement data.
	 *
	 * @return the user uuid of this requirement data
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this requirement data.
	 *
	 * @param userUuid the user uuid of this requirement data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this requirement data.
	 *
	 * @return the create date of this requirement data
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this requirement data.
	 *
	 * @param createDate the create date of this requirement data
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this requirement data.
	 *
	 * @return the modified date of this requirement data
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this requirement data.
	 *
	 * @param modifiedDate the modified date of this requirement data
	 */
	public void setModifiedDate(Date modifiedDate);

}