/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tcpl.sas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SkillSet service. Represents a row in the &quot;skillset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tcpl.sas.model.impl.SkillSetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tcpl.sas.model.impl.SkillSetImpl</code>.
 * </p>
 *
 * @author Rakshansh
 * @see SkillSet
 * @generated
 */
@ProviderType
public interface SkillSetModel extends BaseModel<SkillSet> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a skill set model instance should use the {@link SkillSet} interface instead.
	 */

	/**
	 * Returns the primary key of this skill set.
	 *
	 * @return the primary key of this skill set
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this skill set.
	 *
	 * @param primaryKey the primary key of this skill set
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this skill set.
	 *
	 * @return the uuid of this skill set
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this skill set.
	 *
	 * @param uuid the uuid of this skill set
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the skill set ID of this skill set.
	 *
	 * @return the skill set ID of this skill set
	 */
	public long getSkillSetId();

	/**
	 * Sets the skill set ID of this skill set.
	 *
	 * @param skillSetId the skill set ID of this skill set
	 */
	public void setSkillSetId(long skillSetId);

	/**
	 * Returns the skill set name of this skill set.
	 *
	 * @return the skill set name of this skill set
	 */
	@AutoEscape
	public String getSkillSetName();

	/**
	 * Sets the skill set name of this skill set.
	 *
	 * @param skillSetName the skill set name of this skill set
	 */
	public void setSkillSetName(String skillSetName);

	/**
	 * Returns the group ID of this skill set.
	 *
	 * @return the group ID of this skill set
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this skill set.
	 *
	 * @param groupId the group ID of this skill set
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this skill set.
	 *
	 * @return the user ID of this skill set
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this skill set.
	 *
	 * @param userId the user ID of this skill set
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this skill set.
	 *
	 * @return the user uuid of this skill set
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this skill set.
	 *
	 * @param userUuid the user uuid of this skill set
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this skill set.
	 *
	 * @return the create date of this skill set
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this skill set.
	 *
	 * @param createDate the create date of this skill set
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this skill set.
	 *
	 * @return the modified date of this skill set
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this skill set.
	 *
	 * @param modifiedDate the modified date of this skill set
	 */
	public void setModifiedDate(Date modifiedDate);

}