/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tcpl.sas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SourceVendor service. Represents a row in the &quot;sourcevendor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tcpl.sas.model.impl.SourceVendorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tcpl.sas.model.impl.SourceVendorImpl</code>.
 * </p>
 *
 * @author Rakshansh
 * @see SourceVendor
 * @generated
 */
@ProviderType
public interface SourceVendorModel extends BaseModel<SourceVendor> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a source vendor model instance should use the {@link SourceVendor} interface instead.
	 */

	/**
	 * Returns the primary key of this source vendor.
	 *
	 * @return the primary key of this source vendor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this source vendor.
	 *
	 * @param primaryKey the primary key of this source vendor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the source vendor ID of this source vendor.
	 *
	 * @return the source vendor ID of this source vendor
	 */
	public long getSourceVendorId();

	/**
	 * Sets the source vendor ID of this source vendor.
	 *
	 * @param sourceVendorId the source vendor ID of this source vendor
	 */
	public void setSourceVendorId(long sourceVendorId);

	/**
	 * Returns the emp name of this source vendor.
	 *
	 * @return the emp name of this source vendor
	 */
	@AutoEscape
	public String getEmpName();

	/**
	 * Sets the emp name of this source vendor.
	 *
	 * @param empName the emp name of this source vendor
	 */
	public void setEmpName(String empName);

	/**
	 * Returns the emp email of this source vendor.
	 *
	 * @return the emp email of this source vendor
	 */
	@AutoEscape
	public String getEmpEmail();

	/**
	 * Sets the emp email of this source vendor.
	 *
	 * @param empEmail the emp email of this source vendor
	 */
	public void setEmpEmail(String empEmail);

	/**
	 * Returns the emp mobile of this source vendor.
	 *
	 * @return the emp mobile of this source vendor
	 */
	@AutoEscape
	public String getEmpMobile();

	/**
	 * Sets the emp mobile of this source vendor.
	 *
	 * @param empMobile the emp mobile of this source vendor
	 */
	public void setEmpMobile(String empMobile);

	/**
	 * Returns the emp dob of this source vendor.
	 *
	 * @return the emp dob of this source vendor
	 */
	public Date getEmpDob();

	/**
	 * Sets the emp dob of this source vendor.
	 *
	 * @param empDob the emp dob of this source vendor
	 */
	public void setEmpDob(Date empDob);

	/**
	 * Returns the emp experience of this source vendor.
	 *
	 * @return the emp experience of this source vendor
	 */
	public long getEmpExperience();

	/**
	 * Sets the emp experience of this source vendor.
	 *
	 * @param empExperience the emp experience of this source vendor
	 */
	public void setEmpExperience(long empExperience);

	/**
	 * Returns the emp location of this source vendor.
	 *
	 * @return the emp location of this source vendor
	 */
	@AutoEscape
	public String getEmpLocation();

	/**
	 * Sets the emp location of this source vendor.
	 *
	 * @param empLocation the emp location of this source vendor
	 */
	public void setEmpLocation(String empLocation);

	/**
	 * Returns the cv ID of this source vendor.
	 *
	 * @return the cv ID of this source vendor
	 */
	public long getCvId();

	/**
	 * Sets the cv ID of this source vendor.
	 *
	 * @param cvId the cv ID of this source vendor
	 */
	public void setCvId(long cvId);

	/**
	 * Returns the cv path of this source vendor.
	 *
	 * @return the cv path of this source vendor
	 */
	@AutoEscape
	public String getCvPath();

	/**
	 * Sets the cv path of this source vendor.
	 *
	 * @param cvPath the cv path of this source vendor
	 */
	public void setCvPath(String cvPath);

	/**
	 * Returns the status by customer of this source vendor.
	 *
	 * @return the status by customer of this source vendor
	 */
	@AutoEscape
	public String getStatusByCustomer();

	/**
	 * Sets the status by customer of this source vendor.
	 *
	 * @param statusByCustomer the status by customer of this source vendor
	 */
	public void setStatusByCustomer(String statusByCustomer);

	/**
	 * Returns the status by rm of this source vendor.
	 *
	 * @return the status by rm of this source vendor
	 */
	public Boolean getStatusByRM();

	/**
	 * Sets the status by rm of this source vendor.
	 *
	 * @param statusByRM the status by rm of this source vendor
	 */
	public void setStatusByRM(Boolean statusByRM);

	/**
	 * Returns the deployed on customer of this source vendor.
	 *
	 * @return the deployed on customer of this source vendor
	 */
	public Boolean getDeployedOnCustomer();

	/**
	 * Sets the deployed on customer of this source vendor.
	 *
	 * @param deployedOnCustomer the deployed on customer of this source vendor
	 */
	public void setDeployedOnCustomer(Boolean deployedOnCustomer);

	/**
	 * Returns the group ID of this source vendor.
	 *
	 * @return the group ID of this source vendor
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this source vendor.
	 *
	 * @param groupId the group ID of this source vendor
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this source vendor.
	 *
	 * @return the user ID of this source vendor
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this source vendor.
	 *
	 * @param userId the user ID of this source vendor
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this source vendor.
	 *
	 * @return the user uuid of this source vendor
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this source vendor.
	 *
	 * @param userUuid the user uuid of this source vendor
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this source vendor.
	 *
	 * @return the create date of this source vendor
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this source vendor.
	 *
	 * @param createDate the create date of this source vendor
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this source vendor.
	 *
	 * @return the modified date of this source vendor
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this source vendor.
	 *
	 * @param modifiedDate the modified date of this source vendor
	 */
	public void setModifiedDate(Date modifiedDate);

}