/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tcpl.sas.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.tcpl.sas.model.SourceVendor;
import com.tcpl.sas.service.SourceVendorService;
import com.tcpl.sas.service.persistence.EvalVendorPersistence;
import com.tcpl.sas.service.persistence.RequirementDataPersistence;
import com.tcpl.sas.service.persistence.SkillSetPersistence;
import com.tcpl.sas.service.persistence.SourceVendorPersistence;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the source vendor remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.tcpl.sas.service.impl.SourceVendorServiceImpl}.
 * </p>
 *
 * @author Rakshansh
 * @see com.tcpl.sas.service.impl.SourceVendorServiceImpl
 * @generated
 */
public abstract class SourceVendorServiceBaseImpl
	extends BaseServiceImpl
	implements SourceVendorService, AopService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SourceVendorService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.tcpl.sas.service.SourceVendorServiceUtil</code>.
	 */
	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SourceVendorService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		sourceVendorService = (SourceVendorService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SourceVendorService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SourceVendor.class;
	}

	protected String getModelClassName() {
		return SourceVendor.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = sourceVendorPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@Reference
	protected EvalVendorPersistence evalVendorPersistence;

	@Reference
	protected RequirementDataPersistence requirementDataPersistence;

	@Reference
	protected SkillSetPersistence skillSetPersistence;

	@Reference
	protected com.tcpl.sas.service.SourceVendorLocalService
		sourceVendorLocalService;

	protected SourceVendorService sourceVendorService;

	@Reference
	protected SourceVendorPersistence sourceVendorPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}